# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1b54fff2bb78fa81b73cee8412545501559994c66e6bab6361cbe28d4d56cfc7669ccfaa4c308f0501e248faa1d871591c5b0ab38fd1f4cf786a1b93d3505a5

test:
  secret_key_base: e8b7941df1870dccbeac01458f719e1adc2d3d1ccf967b1ae312278e0377c48640dac362c4d4b8282532b27a806dfd7ef3df7a6a8ba6a3ae4a60f92f709631b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
